# Generated by Django 2.2.9 on 2020-02-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0004_auto_20200226_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='answer1',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
