# Generated by Django 2.2.9 on 2020-02-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0002_landmark_image_url'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_landmark',
            field=models.ManyToManyField(to='landmarks.Landmark'),
        ),
    ]
