# Generated by Django 2.2.9 on 2020-02-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
