# Generated by Django 2.2.9 on 2020-02-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0002_landmark_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='answer2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='landmark',
            name='answer3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='landmark',
            name='answer4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='landmark',
            name='c_answer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='landmark',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='landmark',
            name='question',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
