# Generated by Django 2.2.9 on 2020-02-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0003_auto_20200226_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='landmark',
            name='map_query',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
